// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAefeJNZ2uAcozzSQ2neWGmVs0ME9xrNLc',
    appId: '1:413380334875:android:d7af4f5d6d2075bc55efbe',
    messagingSenderId: '413380334875',
    projectId: 'dikantin-polije',
    storageBucket: 'dikantin-polije.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAprXWx3FV1G_MrbXJU_hpuVBndnisuXV8',
    appId: '1:413380334875:ios:5836de48c8d69e4d55efbe',
    messagingSenderId: '413380334875',
    projectId: 'dikantin-polije',
    storageBucket: 'dikantin-polije.firebasestorage.app',
    iosBundleId: 'jtinova.dikantinAppRebuild',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-TpdTZSdync7THK3Fpz7NZ7sU3kmtjs',
    appId: '1:413380334875:web:db48d1d95136d2db55efbe',
    messagingSenderId: '413380334875',
    projectId: 'dikantin-polije',
    authDomain: 'dikantin-polije.firebaseapp.com',
    storageBucket: 'dikantin-polije.firebasestorage.app',
    measurementId: 'G-Y5HJ3CVYV6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAprXWx3FV1G_MrbXJU_hpuVBndnisuXV8',
    appId: '1:413380334875:ios:5836de48c8d69e4d55efbe',
    messagingSenderId: '413380334875',
    projectId: 'dikantin-polije',
    storageBucket: 'dikantin-polije.firebasestorage.app',
    iosBundleId: 'jtinova.dikantinAppRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI-TpdTZSdync7THK3Fpz7NZ7sU3kmtjs',
    appId: '1:413380334875:web:4496955d529fdfb355efbe',
    messagingSenderId: '413380334875',
    projectId: 'dikantin-polije',
    authDomain: 'dikantin-polije.firebaseapp.com',
    storageBucket: 'dikantin-polije.firebasestorage.app',
    measurementId: 'G-76W2YTTQ9F',
  );

}